---
title: "Analysis of Survey WSS Operators Brazil"
date: "Last run: `r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document:
    code_folding: show
bibliography: POPA_WaterSurvey.bib
---
 

# Research Question 1 : PHASE I (Suppliers)

1. If the survey validates the prevailing lack of **efficiency** (high NWR), can we see any correlation with:
<!-- how high is high?  -->
	+ company features (ownership, size, state, urban/rural location, network lenght ...)? 
	+ staff # (ratio: `staff/served pop`) and  _technical capacity_ (ratio:  `technical staff/served pop`)?
	+ systems in place to monitor (metering, leakage, illegality, customer complaints )?
	+ adoption of SWITS / smart technology?
 	
<!-- + ? is the age at all relevant? (2 efficiency etc? ) -->
<!-- + How widespread is metering? (if not enough to catch leakages ... ) -->
<!-- + Is the customer mix (more or less residential relevant)? (2 innovation? / reliability) -->
<!-- + Is the "integration" W & S at all relavant (2 innovation? ) -->


## Process
<!-- - check outliers that could be misleading my summary / correlation -->
<!-- - check correlation  -->
<!-- YES = (Ownership, size, process to detect cland connection)  -->
<!-- NO (% meter, % network yearly inspected, Q24_VolLossMech_Has, Q39_LeaksDetection_Analyzed)  -->
<!-- ? = # staff , ? = SWITS ADOPTION ? = * (?) Is the year of operation * (?) Is thestack of laws connected with efficiency (Expected inverse relation)??  -->

<!-- - DIMENSION REDUCTION  -->
<!-- DECISION TREE / PCA/ MULTIV ANAL /  or some sort of ways to check which explanatory variable is worth keeping  -->

<!-- -  CLUSTER ANALYSIS  -->
<!-- Hierarchical: Start separate and combine -->
<!-- k-means (limited to the NRW related NUMERIC variables? ) -->
<!-- then interpret what you see in the clusters (do they congregate as STATE, ownership, ??? in what % of assigned to cluster 1 are “public”?)  -->

<!-- - DARE I “EXPLAIN”/MODEL  with multivariable regression what “causes” NRW? —— it seems not linear  -->
<!-- OR just “PREDICT” class (>50 NRW // <50 NRW or whatever is the optimal ….. ) based on which info I have ….. I could use BRA as train and MEX as test ????  -->
<!-- LOGISTIC regress  -->


# Research Question 2 : PHASE I (Suppliers)

2. As a proxy for **reliability**, the surveys asks about service interruptions in the past 12 months, the % of network affected and for how long (days). Can we see any correlation with:
<!-- how high is high? (only 3 never had interruptions)  -->
<!-- how much interruption is acceptable for maintennace  -->
	<!-- + What are the mains reasons?  Maintenance // energy -->
	+ What are the main causes of service interruption? 
		+ (Main Reason 1 = maintenance) --> Connection with energy staff _capacity_?  
		+ (Main Reason 2 = energy) --> Connection with energy blackouts...? 
	+ Degree of independence in governance (?) 
	+ Having (effective) CRM systems in place?

## Process
<!-- - most of them are due to maintenance or energy issue (what does that tell me>?)  -->
<!-- - What do I read on the Desk Research about the Energy issue ? what they say about it ?  -->


<!-- - check outliers that could be misleading my summary / correlation -->
<!-- - check correlation  -->
<!-- YES =   -->
<!-- NO =  -->
<!-- ? = # staff , ? = SWITS ADOPTION ? = * (?) Is the year of operation * (?) Is thestack of laws connected with efficiency (Expected inverse relation)??  -->

<!-- - DIMENSION REDUCTION  -->
<!-- DECISION TREE / PCA/ MULTIV ANAL /  or some sort of ways to check which explanatory variable is worth keeping  -->

<!-- -  CLUSTER ANALYSIS  -->
<!-- Hierarchical: Start separate and combine -->
<!-- k-means (limited to the RELIAB related NUMERIC variables? ) -->
<!-- then interpret what you see in the clusters (do they congregate as STATE, ownership, ??? in what % of assigned to cluster 1 are “public”?)  -->

<!-- - DARE I “EXPLAIN” with multivariable regression what “causes” NRW?  -->



3. Certain suppliers involved in alleged **corruption** / changes of ownership occurred around survey 
	+ refer to Desk Research... 



## Process



# Research Question 3: PHASE I (Suppliers) & PHASE 2 (Households)

4. (In combination PHASE I & PHASE II<!--  // GWI? // Darcia's Note-->) could explore outcome **affordability** & (possibly) related variables to explore:  
	+ Financial assets
		+ Relevant tariff scheme
	+ Financial efficiency tools
	+ Governance structure  


## Process


# Research Question 4: PHASE I (Suppliers) & PHASE 2 (Households)

4. (In combination PHASE I & PHASE II<!--  // GWI? // Darcia's Note-->) could explore outcome **quality** & (possibly) related variables to explore:  
	+ ...
	+ ...
	+ ...
	


## Process


