---
title: "Home"
date: "Last run: `r format(Sys.time(), '%B %e, %Y')`"
output: 
  html_document:
    code_folding: hide
bibliography: POPA_WaterSurvey.bib
---
 

## Project title
Survey of WSS Suppliers in Brazil

### Link to joined survey in MEXICO 

## Purpose of the study
The survey is part of a larger effort to collect original data in preparation of the publication **"Development in America" 2020** that will focus on Infrastructure (Energy, Water and Transportation) sector in LAC. 

## Background and significance


## Inputs from the Literature & Hypothesis 

+ **EFFICIENCY** is a major challenge for LAC WSS suppliers [@garzon_desafios_2016, p6] (also validated by  generally _high levels of water loss, or Non-Revenue Water (NRW)_ in survey the)
+ Lack of **productivity** and active efforts in **maintenance** [@garzon_desafios_2016, p6]
+ **URBANIZATION** is associated to higher consumption per capita (-) / as well as could reduce unit cost of networks (+) —> hence the effects of urbanization as a paradigm shift for the sector are mixed [@arias_regulation_2019, p.35] 

#### Hypothesis
+ **H1**: Given that politicians tend to prioritize visible projects, higher rates of political interference in firm management could lead to higher access rates, but lower quality of service. 
+ **H2**: Increasing a firm’s transparency can increase client confidence & trust, which in turn could boost bill payment rates. 
+ **H3**: Good O&M practices are associated with less service interruptions and higher water quality
+ **H4**: [@arniella_can_2018] SWIT as an alternative to cost-intensive replacement of aging and old by prolonging theyr quality performance. Especially using pressure management schemes has shown large reductions in water mains' breaks frequency can be achieved, reducing real losses and related costs. _but_ [@arias_regulation_2019, p.9] “digital water / smart metering could reduce costs of identifying leakage, but these savings are actually small compared to the cost of fixing the leakages (huge)”!

  
#### Observations from field work (dialogue with POPA)

+ In Brazil there is an ongoing change in ownership regulation for utilities  
+ Private companies are becoming bigger (recent mergers and agglomerations observed among sampled suppliers) 
+ Mixed performance could be related to the fact that in the past private companies were not vey transparent. It is likely that being traded in the public stock market may incentivize more transparent governance 
+ <!-- + AEGEA, Igua SaNEAMENTO --> Suppliers that have been recently involved in corruption-related investigations have been bought soon after  


## Research Question(s)

1. If the survey validates the prevailing lack of **efficiency** (high NWR), can we see any correlation with:
<!-- how high is high?  -->
	+ company features (ownership, size, state, urban/rural location, network lenght ...)? 
	+ human resources (estimated by `staff/served pop ratio`) and  _technical capacity_ (`technical staff/served pop ratio`)?
	+ systems in place to monitor (metering, leakage, illegality, customer complaints )?
	+ degree of adoption of SWITS / smart technology?
 	
<!-- + ? is the age at all relevant? (2 efficiency etc? ) -->
<!-- + How widespread is metering? (if not enough to catch leakages ... ) -->
<!-- + Is the customer mix (more or less residential relevant)? (2 innovation? / reliability) -->
<!-- + Is the "integration" W & S at all relavant (2 innovation? ) -->


2. As a proxy for **reliability**, the surveys asks about service interruptions in the past 12 months, the % of network affected and for how long (days). What are the main causes of service interruption? 
<!-- how high is high? (only 3 never had interruptions)  -->
<!-- how much interruption is acceptable for maintennace  -->
	<!-- + What are the mains reasons?  Maintenance // energy -->
	+ (Main Reason 1 = maintenance) --> Connection with energy staff _capacity_?  
	+ (Main Reason 2 = energy) --> Connection with energy blackouts...? 
 
	Can we see any correlation with:
	
 	+ Degree of independence in governance?
	+ Having (effective) CRM systems in place?

3. Certain suppliers involved in alleged **corruption** / changes of ownership occurred around survey 
	+ refer to POPA Desk Research... 

4. `PHASE I (Suppliers) & PHASE 2 (Households)` Explore outcome **affordability** & (possibly) related variables to explore:  
	+ Financial assets
		+ Relevant tariff scheme
	+ Financial efficiency tools
	+ Governance structure  

<!-- ## 5. Research Question(s) If I had historical and gegographic data 
	+ What is the effect on key outcome (efficiency / reliab) of the underlying trends of population ? (tot, urban / rural / density)
	 "Pop growth in urban areas has been greater than overal pop growth in most countries between 2000 and 2015"
   +  Are megacities still growing or are the secondary cities appearing?  
				UN DATA (forecast + cities)
				https://population.un.org/wup/Download/
					Total urban rural by country 1950-2050 // urbanization by country 1950-2050
				POPULATION DENSITY FREE data
				http://sedac.ciesin.columbia.edu/data/collection/gpw-v4/sets/browse
				http://nelson.wisc.edu/sage/data-and-models/schneider-readme.php
	 **SAVED STUFF** ./01_rawdata/Hist_GWI_POP/cities_pop_tar.Rdata") with GWI data 2011-2017 + POP data 1950 2035 
 	 https://mran.microsoft.com/snapshot/2015-11-17/web/packages/tmap/vignettes/tmap-nutshell.html
	
	+  Effect of HUMAN MADE OVERARCHING TRENDS? 
	+  NATURAL OVERARCHING TRENDS 
			+ climate change ..
			+ water stress // water scarcity -->


 
## Methods and analysis

## Sampling and subject selection

## Data Security and participant privacy

## Survey Instrument PHASE I

```{r tbl_Quest, echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE, results="asis"}
 load(here::here("output", "Quest_BRA1_Key.Rdata"))

edb_var_descriptions <- Quest_BRA1_Key %>%
  dplyr::mutate(Variable = paste0("`", Variable_Eng, "`")) %>% 
	dplyr::select(Variable, "Unit of Analysis" = unit_of_analysis, "Question (Portuguese)" =  Question_Port,"Answer (Portuguese)" = Answer_Port)


caption <- "Questionnaire Intrument (Portuguese) with corresponding Variables"
tbl_var_descriptions <- pandoc.table.return(edb_var_descriptions, 
														  caption = caption,
														  keep.line.breaks = F, 
														  style = "multiline",  
														  split.table = Inf, # so don't break
														  justify = "llll",
														  missing = "" )

cat(tbl_var_descriptions)
```





